using Microsoft.EntityFrameworkCore.Migrations;

namespace gql.Migrations
{
    public partial class nullDescription2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Chapters",
                columns: table => new
                {
                    ChapterId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    WorkId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Act = table.Column<int>(type: "int", nullable: false),
                    Scene = table.Column<int>(type: "int", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Chapters", x => x.ChapterId);
                });

            migrationBuilder.CreateTable(
                name: "Platforms",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LicenseKey = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Platforms", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Commands",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    HowTo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CommandLine = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PlatformId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Commands", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Commands_Platforms_PlatformId",
                        column: x => x.PlatformId,
                        principalTable: "Platforms",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18704, 1, "DUKE ORSINO’s palace.", 1, "12night" },
                    { 19326, 5, "Pomfret castle.", 5, "richard2" },
                    { 19327, 5, "Windsor castle.", 6, "richard2" },
                    { 19328, 1, "London. A street.", 1, "richard3" },
                    { 19329, 1, "The same. Another street.", 2, "richard3" },
                    { 19330, 1, "The palace.", 3, "richard3" },
                    { 19331, 1, "London. The Tower.", 4, "richard3" },
                    { 19332, 2, "London. The palace.", 1, "richard3" },
                    { 19333, 2, "The palace.", 2, "richard3" },
                    { 19334, 2, "London. A street.", 3, "richard3" },
                    { 19335, 2, "London. The palace.", 4, "richard3" },
                    { 19336, 3, "London. A street.", 1, "richard3" },
                    { 19337, 3, "Before Lord Hastings’ house.", 2, "richard3" },
                    { 19338, 3, "Pomfret Castle.", 3, "richard3" },
                    { 19339, 3, "The Tower of London.", 4, "richard3" },
                    { 19340, 3, "The Tower-walls.", 5, "richard3" },
                    { 19341, 3, "The same.", 6, "richard3" },
                    { 19342, 3, "Baynard’s Castle.", 7, "richard3" },
                    { 19343, 4, "Before the Tower.", 1, "richard3" },
                    { 19344, 4, "London. The palace.", 2, "richard3" },
                    { 19345, 4, "The same.", 3, "richard3" },
                    { 19346, 4, "Before the palace.", 4, "richard3" },
                    { 19347, 4, "Lord Derby’s house.", 5, "richard3" },
                    { 19348, 5, "Salisbury. An open place.", 1, "richard3" },
                    { 19349, 5, "The camp near Tamworth.", 2, "richard3" },
                    { 19350, 5, "Bosworth Field.", 3, "richard3" },
                    { 19325, 5, "The same.", 4, "richard2" },
                    { 19324, 5, "A royal palace.", 3, "richard2" },
                    { 19323, 5, "The DUKE OF YORK’s palace.", 2, "richard2" },
                    { 19322, 5, "London. A street leading to the Tower.", 1, "richard2" },
                    { 19296, 4, "Mytilene. A room in a brothel.", 2, "pericles" },
                    { 19297, 4, "Tarsus. A room in CLEON’s house.", 3, "pericles" },
                    { 19298, 4, "Chorus.", 4, "pericles" },
                    { 19299, 4, "Mytilene. A street before the brothel.", 5, "pericles" },
                    { 19300, 4, "The same. A room in the brothel.", 6, "pericles" },
                    { 19301, 5, "Chorus.", 0, "pericles" },
                    { 19302, 5, "On board PERICLES’ ship, off Mytilene. A close", 1, "pericles" },
                    { 19303, 5, "Chorus.", 2, "pericles" },
                    { 19304, 5, "The temple of Diana at Ephesus; THAISA standing", 3, "pericles" },
                    { 19305, 1, "The Phoenix and the Turtle", 1, "phoenixturtle" },
                    { 19306, 1, "Dedication", 0, "rapelucrece" },
                    { 19307, 1, "The Argument", 1, "rapelucrece" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19351, 5, "Another part of the field.", 4, "richard3" },
                    { 19308, 1, "The Rape of Lucrece", 2, "rapelucrece" },
                    { 19310, 1, "The DUKE OF LANCASTER’S palace.", 2, "richard2" },
                    { 19311, 1, "The lists at Coventry.", 3, "richard2" },
                    { 19312, 1, "The court.", 4, "richard2" },
                    { 19313, 2, "Ely House.", 1, "richard2" },
                    { 19314, 2, "The palace.", 2, "richard2" },
                    { 19315, 2, "Wilds in Gloucestershire.", 3, "richard2" },
                    { 19316, 2, "A camp in Wales.", 4, "richard2" },
                    { 19317, 3, "Bristol. Before the castle.", 1, "richard2" },
                    { 19318, 3, "The coast of Wales. A castle in view.", 2, "richard2" },
                    { 19319, 3, "Wales. Before Flint castle.", 3, "richard2" },
                    { 19320, 3, "LANGLEY. The DUKE OF YORK’s garden.", 4, "richard2" },
                    { 19321, 4, "Westminster Hall.", 1, "richard2" },
                    { 19309, 1, "London. KING RICHARD II’s palace.", 1, "richard2" },
                    { 19295, 4, "Tarsus. An open place near the sea-shore.", 1, "pericles" },
                    { 19352, 5, "Another part of the field.", 5, "richard3" },
                    { 19354, 1, "Verona. A public place.", 1, "romeojuliet" },
                    { 19385, 1, "---", 7, "sonnets" },
                    { 19386, 1, "---", 8, "sonnets" },
                    { 19387, 1, "---", 9, "sonnets" },
                    { 19388, 1, "---\r\n", 10, "sonnets" },
                    { 19389, 1, "---\r\n", 11, "sonnets" },
                    { 19390, 1, "---\r\n", 12, "sonnets" },
                    { 19391, 1, "---\r\n", 13, "sonnets" },
                    { 19392, 1, "---\r\n", 14, "sonnets" },
                    { 19393, 1, "---\r\n", 15, "sonnets" },
                    { 19394, 1, "---\r\n", 16, "sonnets" },
                    { 19395, 1, "---\r\n", 17, "sonnets" },
                    { 19396, 1, "---\r\n", 18, "sonnets" },
                    { 19397, 1, "---\r\n", 19, "sonnets" },
                    { 19398, 1, "---\r\n", 20, "sonnets" },
                    { 19399, 1, "---\r\n", 21, "sonnets" },
                    { 19400, 1, "---\r\n", 22, "sonnets" },
                    { 19401, 1, "---\r\n", 23, "sonnets" },
                    { 19402, 1, "---\r\n", 24, "sonnets" },
                    { 19403, 1, "---\r\n", 25, "sonnets" },
                    { 19404, 1, "---\r\n", 26, "sonnets" },
                    { 19405, 1, "---\r\n", 27, "sonnets" },
                    { 19406, 1, "---\r\n", 28, "sonnets" },
                    { 19407, 1, "---\r\n", 29, "sonnets" },
                    { 19408, 1, "---\r\n", 30, "sonnets" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19409, 1, "---\r\n", 31, "sonnets" },
                    { 19384, 1, "---", 6, "sonnets" },
                    { 19383, 1, "---", 5, "sonnets" },
                    { 19382, 1, "---", 4, "sonnets" },
                    { 19381, 1, "---", 3, "sonnets" },
                    { 19355, 1, "A street.", 2, "romeojuliet" },
                    { 19356, 1, "A room in Capulet’s house.", 3, "romeojuliet" },
                    { 19357, 1, "A street.", 4, "romeojuliet" },
                    { 19358, 1, "A hall in Capulet’s house.", 5, "romeojuliet" },
                    { 19359, 2, "Prologue.", 0, "romeojuliet" },
                    { 19360, 2, "A lane by the wall of Capulet’s orchard.", 1, "romeojuliet" },
                    { 19361, 2, "Capulet’s orchard.", 2, "romeojuliet" },
                    { 19362, 2, "Friar Laurence’s cell.", 3, "romeojuliet" },
                    { 19363, 2, "A street.", 4, "romeojuliet" },
                    { 19364, 2, "Capulet’s orchard.", 5, "romeojuliet" },
                    { 19365, 2, "Friar Laurence’s cell.", 6, "romeojuliet" },
                    { 19366, 3, "A public place.", 1, "romeojuliet" },
                    { 19353, 0, "Verona: Mantua.", 1, "romeojuliet" },
                    { 19367, 3, "Capulet’s orchard.", 2, "romeojuliet" },
                    { 19369, 3, "A room in Capulet’s house.", 4, "romeojuliet" },
                    { 19370, 3, "Capulet’s orchard.", 5, "romeojuliet" },
                    { 19371, 4, "Friar Laurence’s cell.", 1, "romeojuliet" },
                    { 19372, 4, "Hall in Capulet’s house.", 2, "romeojuliet" },
                    { 19373, 4, "Juliet’s chamber.", 3, "romeojuliet" },
                    { 19374, 4, "Hall in Capulet’s house.", 4, "romeojuliet" },
                    { 19375, 4, "Juliet’s chamber.", 5, "romeojuliet" },
                    { 19376, 5, "Mantua. A street.", 1, "romeojuliet" },
                    { 19377, 5, "Friar Laurence’s cell.", 2, "romeojuliet" },
                    { 19378, 5, "A churchyard; in it a tomb belonging to the Capulets.", 3, "romeojuliet" },
                    { 19379, 1, "---", 1, "sonnets" },
                    { 19380, 1, "---", 2, "sonnets" },
                    { 19368, 3, "Friar Laurence’s cell.", 3, "romeojuliet" },
                    { 19410, 1, "---\r\n", 32, "sonnets" },
                    { 19294, 4, "Near the seashore.", 0, "pericles" },
                    { 19292, 3, "Tarsus. A room in CLEON’s house.", 3, "pericles" },
                    { 19208, 4, "A room in the Garter Inn.", 3, "merrywives" },
                    { 19209, 4, "A room in FORD’S house.", 4, "merrywives" },
                    { 19210, 4, "A room in the Garter Inn.", 5, "merrywives" },
                    { 19211, 4, "Another room in the Garter Inn.", 6, "merrywives" },
                    { 19212, 5, "A room in the Garter Inn.", 1, "merrywives" },
                    { 19213, 5, "Windsor Park.", 2, "merrywives" },
                    { 19214, 5, "A street leading to the Park.", 3, "merrywives" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19215, 5, "Windsor Park.", 4, "merrywives" },
                    { 19216, 5, "Another part of the Park.", 5, "merrywives" },
                    { 19217, 1, "Athens. The palace of THESEUS.", 1, "midsummer" },
                    { 19218, 1, "Athens. QUINCE’S house.", 2, "midsummer" },
                    { 19219, 2, "A wood near Athens.", 1, "midsummer" },
                    { 19220, 2, "Another part of the wood.", 2, "midsummer" },
                    { 19221, 3, "The wood. TITANIA lying asleep.", 1, "midsummer" },
                    { 19222, 3, "Another part of the wood.", 2, "midsummer" },
                    { 19223, 4, "The same. LYSANDER, DEMETRIUS, HELENA, and HERMIA", 1, "midsummer" },
                    { 19224, 4, "Athens. QUINCE’S house.", 2, "midsummer" },
                    { 19225, 5, "Athens. The palace of THESEUS.", 1, "midsummer" },
                    { 19226, 1, "Before LEONATO’S house.", 1, "muchado" },
                    { 19227, 1, "A room in LEONATO’s house.", 2, "muchado" },
                    { 19228, 1, "The same.", 3, "muchado" },
                    { 19229, 2, "A hall in LEONATO’S house.", 1, "muchado" },
                    { 19230, 2, "The same.", 2, "muchado" },
                    { 19231, 2, "LEONATO’S orchard.", 3, "muchado" },
                    { 19232, 3, "LEONATO’S garden.", 1, "muchado" },
                    { 19207, 4, "A room in FORD’S house.", 2, "merrywives" },
                    { 19206, 4, "A street.", 1, "merrywives" },
                    { 19205, 3, "A room in the Garter Inn.", 5, "merrywives" },
                    { 19204, 3, "A room in PAGE’S house.", 4, "merrywives" },
                    { 19178, 2, "Venice. A street.", 2, "merchantvenice" },
                    { 19179, 2, "The same. A room in SHYLOCK’S house.", 3, "merchantvenice" },
                    { 19180, 2, "The same. A street.", 4, "merchantvenice" },
                    { 19181, 2, "The same. Before SHYLOCK’S house.", 5, "merchantvenice" },
                    { 19182, 2, "The same.", 6, "merchantvenice" },
                    { 19183, 2, "Belmont. A room in PORTIA’S house.", 7, "merchantvenice" },
                    { 19184, 2, "Venice. A street.", 8, "merchantvenice" },
                    { 19185, 2, "Belmont. A room in PORTIA’S house.", 9, "merchantvenice" },
                    { 19186, 3, "Venice. A street.", 1, "merchantvenice" },
                    { 19187, 3, "Belmont. A room in PORTIA’S house.", 2, "merchantvenice" },
                    { 19188, 3, "Venice. A street.", 3, "merchantvenice" },
                    { 19189, 3, "Belmont. A room in PORTIA’S house.", 4, "merchantvenice" },
                    { 19233, 3, "A room in LEONATO’S house", 2, "muchado" },
                    { 19190, 3, "The same. A garden.", 5, "merchantvenice" },
                    { 19192, 4, "The same. A street.", 2, "merchantvenice" },
                    { 19193, 5, "Belmont. Avenue to PORTIA’S house.", 1, "merchantvenice" },
                    { 19194, 1, "Windsor. Before PAGE’s house.", 1, "merrywives" },
                    { 19195, 1, "The same.", 2, "merrywives" },
                    { 19196, 1, "A room in the Garter Inn.", 3, "merrywives" },
                    { 19197, 1, "A room in DOCTOR CAIUS’ house.", 4, "merrywives" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19198, 2, "Before PAGE’S house.", 1, "merrywives" },
                    { 19199, 2, "A room in the Garter Inn.", 2, "merrywives" },
                    { 19200, 2, "A field near Windsor.", 3, "merrywives" },
                    { 19201, 3, "A field near Frogmore.", 1, "merrywives" },
                    { 19202, 3, "A street.", 2, "merrywives" },
                    { 19203, 3, "A room in FORD’S house.", 3, "merrywives" },
                    { 19191, 4, "Venice. A court of justice.", 1, "merchantvenice" },
                    { 19293, 3, "Ephesus. A room in CERIMON’s house.", 4, "pericles" },
                    { 19234, 3, "A street.", 3, "muchado" },
                    { 19236, 3, "Another room in LEONATO’S house.", 5, "muchado" },
                    { 19267, 1, "---\r\n", 10, "passionatepilgrim" },
                    { 19268, 1, "---\r\n", 11, "passionatepilgrim" },
                    { 19269, 1, "---\r\n", 12, "passionatepilgrim" },
                    { 19270, 1, "---\r\n", 13, "passionatepilgrim" },
                    { 19271, 1, "---\r\n", 14, "passionatepilgrim" },
                    { 19272, 1, "---\r\n", 15, "passionatepilgrim" },
                    { 19273, 1, "Sonnet to sundry notes of music\r\n", 16, "passionatepilgrim" },
                    { 19274, 1, "Sonnet to sundry notes of music\r\n", 17, "passionatepilgrim" },
                    { 19275, 1, "Sonnet to sundry notes of music\r\n", 18, "passionatepilgrim" },
                    { 19276, 1, "Sonnet to sundry notes of music\r\n", 19, "passionatepilgrim" },
                    { 19277, 1, "Sonnet to sundry notes of music\r\n", 20, "passionatepilgrim" },
                    { 19278, 1, "Sonnet to sundry notes of music\r\n", 21, "passionatepilgrim" },
                    { 19279, 1, "Prologue.", 0, "pericles" },
                    { 19280, 1, "Antioch. A room in the palace.", 1, "pericles" },
                    { 19281, 1, "Tyre. A room in the palace.", 2, "pericles" },
                    { 19282, 1, "Tyre. An ante-chamber in the palace.", 3, "pericles" },
                    { 19283, 1, "Tarsus. A room in the Governor’s house.", 4, "pericles" },
                    { 19284, 2, "Pentapolis. An open place by the sea-side.", 1, "pericles" },
                    { 19285, 2, "The same. A public way or platform leading to the", 2, "pericles" },
                    { 19286, 2, "The same. A hall of state: a banquet prepared.", 3, "pericles" },
                    { 19287, 2, "Tyre. A room in the Governor’s house.", 4, "pericles" },
                    { 19288, 2, "Pentapolis. A room in the palace.", 5, "pericles" },
                    { 19289, 3, "Chorus.", 0, "pericles" },
                    { 19290, 3, "On ship.", 1, "pericles" },
                    { 19291, 3, "Ephesus. A room in CERIMON’s house.", 2, "pericles" },
                    { 19266, 1, "---", 9, "passionatepilgrim" },
                    { 19265, 1, "---", 8, "passionatepilgrim" },
                    { 19264, 1, "---", 7, "passionatepilgrim" },
                    { 19263, 1, "---", 6, "passionatepilgrim" },
                    { 19237, 4, "A church.", 1, "muchado" },
                    { 19238, 4, "A prison.", 2, "muchado" },
                    { 19239, 5, "Before LEONATO’S house.", 1, "muchado" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19240, 5, "LEONATO’S garden.", 2, "muchado" },
                    { 19241, 5, "A church.", 3, "muchado" },
                    { 19242, 5, "A room in LEONATO’S house.", 4, "muchado" },
                    { 19243, 1, "Venice. A street.", 1, "othello" },
                    { 19244, 1, "Another street.", 2, "othello" },
                    { 19245, 1, "A council-chamber.", 3, "othello" },
                    { 19246, 2, "A Sea-port in Cyprus. An open place near the quay.", 1, "othello" },
                    { 19247, 2, "A street.", 2, "othello" },
                    { 19248, 2, "A hall in the castle.", 3, "othello" },
                    { 19235, 3, "HERO’s apartment.", 4, "muchado" },
                    { 19249, 3, "Before the castle.", 1, "othello" },
                    { 19251, 3, "The garden of the castle.", 3, "othello" },
                    { 19252, 3, "Before the castle.", 4, "othello" },
                    { 19253, 4, "Cyprus. Before the castle.", 1, "othello" },
                    { 19254, 4, "A room in the castle.", 2, "othello" },
                    { 19255, 4, "Another room in the castle.", 3, "othello" },
                    { 19256, 5, "Cyprus. A street.", 1, "othello" },
                    { 19257, 5, "A bedchamber in the castle: DESDEMONA in bed asleep;", 2, "othello" },
                    { 19258, 1, "---", 1, "passionatepilgrim" },
                    { 19259, 1, "---", 2, "passionatepilgrim" },
                    { 19260, 1, "---", 3, "passionatepilgrim" },
                    { 19261, 1, "---", 4, "passionatepilgrim" },
                    { 19262, 1, "---", 5, "passionatepilgrim" },
                    { 19250, 3, "A room in the castle.", 2, "othello" },
                    { 19411, 1, "---\r\n", 33, "sonnets" },
                    { 19412, 1, "---\r\n", 34, "sonnets" },
                    { 19413, 1, "---\r\n", 35, "sonnets" },
                    { 19563, 3, "The same. A hall in Timon’s house.", 4, "timonathens" },
                    { 19564, 3, "The same. The senate-house. The Senate sitting.", 5, "timonathens" },
                    { 19565, 3, "The same. A banqueting-room in Timon’s house.", 6, "timonathens" },
                    { 19566, 4, "Without the walls of Athens.", 1, "timonathens" },
                    { 19567, 4, "Athens. A room in Timon’s house.", 2, "timonathens" },
                    { 19568, 4, "Woods and cave, near the seashore.", 3, "timonathens" },
                    { 19569, 5, "The woods. Before Timon’s cave.", 1, "timonathens" },
                    { 19570, 5, "Before the walls of Athens.", 2, "timonathens" },
                    { 19571, 5, "The woods. Timon’s cave, and a rude tomb seen.", 3, "timonathens" },
                    { 19572, 5, "Before the walls of Athens.", 4, "timonathens" },
                    { 19573, 1, "Rome. Before the Capitol.", 1, "titus" },
                    { 19574, 2, "Rome. Before the Palace.", 1, "titus" },
                    { 19575, 2, "A forest near Rome. Horns and cry of hounds heard.", 2, "titus" },
                    { 19576, 2, "A lonely part of the forest.", 3, "titus" },
                    { 19577, 2, "Another part of the forest.", 4, "titus" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19578, 3, "Rome. A street.", 1, "titus" },
                    { 19579, 3, "A room in Titus’s house. A banquet set out.", 2, "titus" },
                    { 19580, 4, "Rome. Titus’s garden.", 1, "titus" },
                    { 19581, 4, "The same. A room in the palace.", 2, "titus" },
                    { 19582, 4, "The same. A public place.", 3, "titus" },
                    { 19583, 4, "The same. Before the palace.", 4, "titus" },
                    { 19584, 5, "Plains near Rome.", 1, "titus" },
                    { 19585, 5, "Rome. Before TITUS’s house.", 2, "titus" },
                    { 19586, 5, "Court of TITUS’s house. A banquet set out.", 3, "titus" },
                    { 19587, 1, "Prologue.", 0, "troilus" },
                    { 19562, 3, "A room in Sempronius’ house.", 3, "timonathens" },
                    { 19561, 3, "A public place.", 2, "timonathens" },
                    { 19560, 3, "A room in Lucullus’ house.", 1, "timonathens" },
                    { 19559, 2, "The same. A hall in Timon’s house.", 2, "timonathens" },
                    { 19533, 0, "Before an alehouse on a heath", 1, "tamingshrew" },
                    { 19534, 0, "A bedchamber in the LORD’S house", 2, "tamingshrew" },
                    { 19535, 1, "Padua. A public place", 1, "tamingshrew" },
                    { 19536, 1, "Padua. Before HORTENSIO’S house", 2, "tamingshrew" },
                    { 19537, 2, "Padua. BAPTISTA’S house", 1, "tamingshrew" },
                    { 19538, 3, "Padua. BAPTISTA’S house", 1, "tamingshrew" },
                    { 19539, 3, "Padua. Before BAPTISTA’So house", 2, "tamingshrew" },
                    { 19540, 4, "PETRUCHIO’S country house", 1, "tamingshrew" },
                    { 19541, 4, "Padua. Before BAPTISTA’S house", 2, "tamingshrew" },
                    { 19542, 4, "PETRUCHIO’S house", 3, "tamingshrew" },
                    { 19543, 4, "Padua. Before BAPTISTA’S house", 4, "tamingshrew" },
                    { 19544, 4, "A public road", 5, "tamingshrew" },
                    { 19588, 1, "Troy. Before Priam’s palace.", 1, "troilus" },
                    { 19545, 5, "Padua. Before LUCENTIO’S house", 1, "tamingshrew" },
                    { 19547, 1, "On a ship at sea: a tempestuous noise", 1, "tempest" },
                    { 19548, 1, "The island. Before PROSPERO’S cell.", 2, "tempest" },
                    { 19549, 2, "Another part of the island.", 1, "tempest" },
                    { 19550, 2, "Another part of the island.", 2, "tempest" },
                    { 19551, 3, "Before PROSPERO’S Cell.", 1, "tempest" },
                    { 19552, 3, "Another part of the island.", 2, "tempest" },
                    { 19553, 3, "Another part of the island.", 3, "tempest" },
                    { 19554, 4, "Before PROSPERO’S cell.", 1, "tempest" },
                    { 19555, 5, "Before PROSPERO’S cell.", 1, "tempest" },
                    { 19556, 1, "Athens. A hall in Timon’s house.", 1, "timonathens" },
                    { 19557, 1, "A banqueting-room in Timon’s house.", 2, "timonathens" },
                    { 19558, 2, "A Senator’s house.", 1, "timonathens" },
                    { 19546, 5, "LUCENTIO’S house", 2, "tamingshrew" },
                    { 19532, 1, "---\r\n", 154, "sonnets" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19589, 1, "The Same. A street.", 2, "troilus" },
                    { 19591, 2, "A part of the Grecian camp.", 1, "troilus" },
                    { 19622, 3, "Milan. The DUKE’s palace.", 1, "twogents" },
                    { 19623, 3, "The same. The DUKE’s palace.", 2, "twogents" },
                    { 19624, 4, "The frontiers of Mantua. A forest.", 1, "twogents" },
                    { 19625, 4, "Milan. Outside the DUKE’s palace, under SILVIA’s chamber.", 2, "twogents" },
                    { 19626, 4, "The same.", 3, "twogents" },
                    { 19627, 4, "The same.", 4, "twogents" },
                    { 19628, 5, "Milan. An abbey.", 1, "twogents" },
                    { 19629, 5, "The same. The DUKE’s palace.", 2, "twogents" },
                    { 19630, 5, "The frontiers of Mantua. The forest.", 3, "twogents" },
                    { 19631, 5, "Another part of the forest.", 4, "twogents" },
                    { 19632, 1, "Dedication.", 0, "venusadonis" },
                    { 19633, 1, "Venus and Adonis.", 1, "venusadonis" },
                    { 19634, 1, "Antechamber in LEONTES’ palace.", 1, "winterstale" },
                    { 19635, 1, "A room of state in the same.", 2, "winterstale" },
                    { 19636, 2, "A room in LEONTES’ palace.", 1, "winterstale" },
                    { 19637, 2, "A prison.", 2, "winterstale" },
                    { 19638, 2, "A room in LEONTES’ palace.", 3, "winterstale" },
                    { 19639, 3, "A sea-port in Sicilia.", 1, "winterstale" },
                    { 19640, 3, "A court of Justice.", 2, "winterstale" },
                    { 19641, 3, "Bohemia. A desert country near the sea.", 3, "winterstale" },
                    { 19642, 4, "Chorus as Time speaks.", 1, "winterstale" },
                    { 19643, 4, "Bohemia. The palace of POLIXENES.", 2, "winterstale" },
                    { 19644, 4, "A road near the Shepherd’s cottage.", 3, "winterstale" },
                    { 19645, 4, "The Shepherd’s cottage.", 4, "winterstale" },
                    { 19646, 5, "A room in LEONTES’ palace.", 1, "winterstale" },
                    { 19621, 2, "Verona. JULIA’S house.", 7, "twogents" },
                    { 19620, 2, "The same. The DUKE’S palace.", 6, "twogents" },
                    { 19619, 2, "The same. A street.", 5, "twogents" },
                    { 19618, 2, "Milan. The DUKE’s palace.", 4, "twogents" },
                    { 19592, 2, "Troy. A room in Priam’s palace.", 2, "troilus" },
                    { 19593, 2, "The Grecian camp. Before Achilles’ tent.", 3, "troilus" },
                    { 19594, 3, "Troy. Priam’s palace.", 1, "troilus" },
                    { 19595, 3, "The same. Pandarus’ orchard.", 2, "troilus" },
                    { 19596, 3, "The Grecian camp. Before Achilles’ tent.", 3, "troilus" },
                    { 19597, 4, "Troy. A street.", 1, "troilus" },
                    { 19598, 4, "The same. Court of Pandarus’ house.", 2, "troilus" },
                    { 19599, 4, "The same. Street before Pandarus’ house.", 3, "troilus" },
                    { 19600, 4, "The same. Pandarus’ house.", 4, "troilus" },
                    { 19601, 4, "The Grecian camp. Lists set out.", 5, "troilus" },
                    { 19602, 5, "The Grecian camp. Before Achilles’ tent.", 1, "troilus" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19603, 5, "The same. Before Calchas’ tent.", 2, "troilus" },
                    { 19590, 1, "The Grecian camp. Before Agamemnon’s tent.", 3, "troilus" },
                    { 19604, 5, "Troy. Before Priam’s palace.", 3, "troilus" },
                    { 19606, 5, "Another part of the plains.", 5, "troilus" },
                    { 19607, 5, "Another part of the plains.", 6, "troilus" },
                    { 19608, 5, "Another part of the plains.", 7, "troilus" },
                    { 19609, 5, "Another part of the plains.", 8, "troilus" },
                    { 19610, 5, "Another part of the plains.", 9, "troilus" },
                    { 19611, 5, "Another part of the plains.\r\n", 10, "troilus" },
                    { 19612, 1, "Verona. An open place.", 1, "twogents" },
                    { 19613, 1, "The same. Garden of JULIA’s house.", 2, "twogents" },
                    { 19614, 1, "The same. ANTONIO’s house.", 3, "twogents" },
                    { 19615, 2, "Milan. The DUKE’s palace.", 1, "twogents" },
                    { 19616, 2, "Verona. JULIA’S house.", 2, "twogents" },
                    { 19617, 2, "The same. A street.", 3, "twogents" },
                    { 19605, 5, "Plains between Troy and the Grecian camp.", 4, "troilus" },
                    { 19531, 1, "---\r\n", 153, "sonnets" },
                    { 19530, 1, "---\r\n", 152, "sonnets" },
                    { 19529, 1, "---\r\n", 151, "sonnets" },
                    { 19444, 1, "---\r\n", 66, "sonnets" },
                    { 19445, 1, "---\r\n", 67, "sonnets" },
                    { 19446, 1, "---\r\n", 68, "sonnets" },
                    { 19447, 1, "---\r\n", 69, "sonnets" },
                    { 19448, 1, "---\r\n", 70, "sonnets" },
                    { 19449, 1, "---\r\n", 71, "sonnets" },
                    { 19450, 1, "---\r\n", 72, "sonnets" },
                    { 19451, 1, "---\r\n", 73, "sonnets" },
                    { 19452, 1, "---\r\n", 74, "sonnets" },
                    { 19453, 1, "---\r\n", 75, "sonnets" },
                    { 19454, 1, "---\r\n", 76, "sonnets" },
                    { 19455, 1, "---\r\n", 77, "sonnets" },
                    { 19456, 1, "---\r\n", 78, "sonnets" },
                    { 19457, 1, "---\r\n", 79, "sonnets" },
                    { 19458, 1, "---\r\n", 80, "sonnets" },
                    { 19459, 1, "---\r\n", 81, "sonnets" },
                    { 19460, 1, "---\r\n", 82, "sonnets" },
                    { 19461, 1, "---\r\n", 83, "sonnets" },
                    { 19462, 1, "---\r\n", 84, "sonnets" },
                    { 19463, 1, "---\r\n", 85, "sonnets" },
                    { 19464, 1, "---\r\n", 86, "sonnets" },
                    { 19465, 1, "---\r\n", 87, "sonnets" },
                    { 19466, 1, "---\r\n", 88, "sonnets" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19467, 1, "---\r\n", 89, "sonnets" },
                    { 19468, 1, "---\r\n", 90, "sonnets" },
                    { 19443, 1, "---\r\n", 65, "sonnets" },
                    { 19442, 1, "---\r\n", 64, "sonnets" },
                    { 19441, 1, "---\r\n", 63, "sonnets" },
                    { 19440, 1, "---\r\n", 62, "sonnets" },
                    { 19414, 1, "---\r\n", 36, "sonnets" },
                    { 19415, 1, "---\r\n", 37, "sonnets" },
                    { 19416, 1, "---\r\n", 38, "sonnets" },
                    { 19417, 1, "---\r\n", 39, "sonnets" },
                    { 19418, 1, "---\r\n", 40, "sonnets" },
                    { 19419, 1, "---\r\n", 41, "sonnets" },
                    { 19420, 1, "---\r\n", 42, "sonnets" },
                    { 19421, 1, "---\r\n", 43, "sonnets" },
                    { 19422, 1, "---\r\n", 44, "sonnets" },
                    { 19423, 1, "---\r\n", 45, "sonnets" },
                    { 19424, 1, "---\r\n", 46, "sonnets" },
                    { 19425, 1, "---\r\n", 47, "sonnets" },
                    { 19469, 1, "---\r\n", 91, "sonnets" },
                    { 19426, 1, "---\r\n", 48, "sonnets" },
                    { 19428, 1, "---\r\n", 50, "sonnets" },
                    { 19429, 1, "---\r\n", 51, "sonnets" },
                    { 19430, 1, "---\r\n", 52, "sonnets" },
                    { 19431, 1, "---\r\n", 53, "sonnets" },
                    { 19432, 1, "---\r\n", 54, "sonnets" },
                    { 19433, 1, "---\r\n", 55, "sonnets" },
                    { 19434, 1, "---\r\n", 56, "sonnets" },
                    { 19435, 1, "---\r\n", 57, "sonnets" },
                    { 19436, 1, "---\r\n", 58, "sonnets" },
                    { 19437, 1, "---\r\n", 59, "sonnets" },
                    { 19438, 1, "---\r\n", 60, "sonnets" },
                    { 19439, 1, "---\r\n", 61, "sonnets" },
                    { 19427, 1, "---\r\n", 49, "sonnets" },
                    { 19470, 1, "---\r\n", 92, "sonnets" },
                    { 19471, 1, "---\r\n", 93, "sonnets" },
                    { 19472, 1, "---\r\n", 94, "sonnets" },
                    { 19503, 1, "---\r\n", 125, "sonnets" },
                    { 19504, 1, "---\r\n", 126, "sonnets" },
                    { 19505, 1, "---\r\n", 127, "sonnets" },
                    { 19506, 1, "---\r\n", 128, "sonnets" },
                    { 19507, 1, "---\r\n", 129, "sonnets" },
                    { 19508, 1, "---\r\n", 130, "sonnets" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19509, 1, "---\r\n", 131, "sonnets" },
                    { 19510, 1, "---\r\n", 132, "sonnets" },
                    { 19511, 1, "---\r\n", 133, "sonnets" },
                    { 19512, 1, "---\r\n", 134, "sonnets" },
                    { 19513, 1, "---\r\n", 135, "sonnets" },
                    { 19514, 1, "---\r\n", 136, "sonnets" },
                    { 19502, 1, "---\r\n", 124, "sonnets" },
                    { 19515, 1, "---\r\n", 137, "sonnets" },
                    { 19517, 1, "---\r\n", 139, "sonnets" },
                    { 19518, 1, "---\r\n", 140, "sonnets" },
                    { 19519, 1, "---\r\n", 141, "sonnets" },
                    { 19520, 1, "---\r\n", 142, "sonnets" },
                    { 19521, 1, "---\r\n", 143, "sonnets" },
                    { 19522, 1, "---\r\n", 144, "sonnets" },
                    { 19523, 1, "---\r\n", 145, "sonnets" },
                    { 19524, 1, "---\r\n", 146, "sonnets" },
                    { 19525, 1, "---\r\n", 147, "sonnets" },
                    { 19526, 1, "---\r\n", 148, "sonnets" },
                    { 19527, 1, "---\r\n", 149, "sonnets" },
                    { 19528, 1, "---\r\n", 150, "sonnets" },
                    { 19516, 1, "---\r\n", 138, "sonnets" },
                    { 19177, 2, "Belmont. A room in PORTIA’S house.", 1, "merchantvenice" },
                    { 19501, 1, "---\r\n", 123, "sonnets" },
                    { 19499, 1, "---\r\n", 121, "sonnets" },
                    { 19473, 1, "---\r\n", 95, "sonnets" },
                    { 19474, 1, "---\r\n", 96, "sonnets" },
                    { 19475, 1, "---\r\n", 97, "sonnets" },
                    { 19476, 1, "---\r\n", 98, "sonnets" },
                    { 19477, 1, "---\r\n", 99, "sonnets" },
                    { 19478, 1, "---\r\n", 100, "sonnets" },
                    { 19479, 1, "---\r\n", 101, "sonnets" },
                    { 19480, 1, "---\r\n", 102, "sonnets" },
                    { 19481, 1, "---\r\n", 103, "sonnets" },
                    { 19482, 1, "---\r\n", 104, "sonnets" },
                    { 19483, 1, "---\r\n", 105, "sonnets" },
                    { 19484, 1, "---\r\n", 106, "sonnets" },
                    { 19500, 1, "---\r\n", 122, "sonnets" },
                    { 19485, 1, "---\r\n", 107, "sonnets" },
                    { 19487, 1, "---\r\n", 109, "sonnets" },
                    { 19488, 1, "---\r\n", 110, "sonnets" },
                    { 19489, 1, "---\r\n", 111, "sonnets" },
                    { 19490, 1, "---\r\n", 112, "sonnets" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19491, 1, "---\r\n", 113, "sonnets" },
                    { 19492, 1, "---\r\n", 114, "sonnets" },
                    { 19493, 1, "---\r\n", 115, "sonnets" },
                    { 19494, 1, "---\r\n", 116, "sonnets" },
                    { 19495, 1, "---\r\n", 117, "sonnets" },
                    { 19496, 1, "---\r\n", 118, "sonnets" },
                    { 19497, 1, "---\r\n", 119, "sonnets" },
                    { 19498, 1, "---\r\n", 120, "sonnets" },
                    { 19486, 1, "---\r\n", 108, "sonnets" },
                    { 19647, 5, "Before LEONTES’ palace.", 2, "winterstale" },
                    { 19176, 1, "Venice. A public place.", 3, "merchantvenice" },
                    { 19174, 1, "Venice. A street.", 1, "merchantvenice" },
                    { 18853, 1, "The same. Another room in the palace.", 6, "cymbeline" },
                    { 18854, 2, "Britain. Before Cymbeline’s palace.", 1, "cymbeline" },
                    { 18855, 2, "Imogen’s bedchamber in Cymbeline’s palace:", 2, "cymbeline" },
                    { 18856, 2, "An ante-chamber adjoining Imogen’s apartments.", 3, "cymbeline" },
                    { 18857, 2, "Rome. Philario’s house.", 4, "cymbeline" },
                    { 18858, 2, "Another room in Philario’s house.", 5, "cymbeline" },
                    { 18859, 3, "Britain. A hall in Cymbeline’s palace.", 1, "cymbeline" },
                    { 18860, 3, "Another room in the palace.", 2, "cymbeline" },
                    { 18861, 3, "Wales: a mountainous country with a cave.", 3, "cymbeline" },
                    { 18862, 3, "Country near Milford-Haven.", 4, "cymbeline" },
                    { 18863, 3, "A room in Cymbeline’s palace.", 5, "cymbeline" },
                    { 18864, 3, "Wales. Before the cave of Belarius.", 6, "cymbeline" },
                    { 18865, 3, "Rome. A public place.", 7, "cymbeline" },
                    { 18866, 4, "Wales: near the cave of Belarius.", 1, "cymbeline" },
                    { 18867, 4, "Before the cave of Belarius.", 2, "cymbeline" },
                    { 18868, 4, "A room in Cymbeline’s palace.", 3, "cymbeline" },
                    { 18869, 4, "Wales: before the cave of Belarius.", 4, "cymbeline" },
                    { 18870, 5, "Britain. The Roman camp.", 1, "cymbeline" },
                    { 18871, 5, "Field of battle between the British and Roman camps.", 2, "cymbeline" },
                    { 18872, 5, "Another part of the field.", 3, "cymbeline" },
                    { 18873, 5, "A British prison.", 4, "cymbeline" },
                    { 18874, 5, "Cymbeline’s tent.", 5, "cymbeline" },
                    { 18875, 1, "Elsinore. A platform before the Castle.", 1, "hamlet" },
                    { 18876, 1, "Elsinore. A room of state in the Castle.", 2, "hamlet" },
                    { 18877, 1, "Elsinore. A room in the house of Polonius.", 3, "hamlet" },
                    { 18852, 1, "Britain. A room in Cymbeline’s palace.", 5, "cymbeline" },
                    { 18851, 1, "Rome. Philario’s house.", 4, "cymbeline" },
                    { 18850, 1, "A room in Cymbeline’s palace.", 3, "cymbeline" },
                    { 18849, 1, "The same. A public place.", 2, "cymbeline" },
                    { 18823, 1, "Before Corioli.", 4, "coriolanus" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18824, 1, "Corioli. A street.", 5, "coriolanus" },
                    { 18825, 1, "Near the camp of Cominius.", 6, "coriolanus" },
                    { 18826, 1, "The gates of Corioli.", 7, "coriolanus" },
                    { 18827, 1, "A field of battle.", 8, "coriolanus" },
                    { 18828, 1, "The Roman camp.", 9, "coriolanus" },
                    { 18829, 1, "The camp of the Volsces.\r\n", 10, "coriolanus" },
                    { 18830, 2, "Rome. A public place.", 1, "coriolanus" },
                    { 18831, 2, "The same. The Capitol.", 2, "coriolanus" },
                    { 18832, 2, "The same. The Forum.", 3, "coriolanus" },
                    { 18833, 3, "Rome. A street.", 1, "coriolanus" },
                    { 18834, 3, "A room in CORIOLANUS’S house.", 2, "coriolanus" },
                    { 18878, 1, "Elsinore. The platform before the Castle.", 4, "hamlet" },
                    { 18835, 3, "The same. The Forum.", 3, "coriolanus" },
                    { 18837, 4, "A highway between Rome and Antium.", 3, "coriolanus" },
                    { 18838, 4, "Antium. Before Aufidius’s house.", 4, "coriolanus" },
                    { 18839, 4, "The same. A hall in Aufidius’s house.", 5, "coriolanus" },
                    { 18840, 4, "Rome. A public place.", 6, "coriolanus" },
                    { 18841, 4, "A camp, at a small distance from Rome.", 7, "coriolanus" },
                    { 18842, 5, "Rome. A public place.", 1, "coriolanus" },
                    { 18843, 5, "Entrance of the Volscian camp before Rome.", 2, "coriolanus" },
                    { 18844, 5, "The tent of Coriolanus.", 3, "coriolanus" },
                    { 18845, 5, "Rome. A public place.", 4, "coriolanus" },
                    { 18846, 5, "The same. A street near the gate.", 5, "coriolanus" },
                    { 18847, 5, "Antium. A public place.", 6, "coriolanus" },
                    { 18848, 1, "Britain. The garden of Cymbeline’s palace.", 1, "cymbeline" },
                    { 18836, 4, "The same. A street near the gate.", 2, "coriolanus" },
                    { 18822, 1, "Rome. A room in CORIOLANUS’ house.", 3, "coriolanus" },
                    { 18879, 1, "Elsinore. The Castle. Another part of the fortifications.", 5, "hamlet" },
                    { 18881, 2, "Elsinore. A room in the Castle.", 2, "hamlet" },
                    { 18912, 5, "Another part of the field.", 4, "henry4p1" },
                    { 18913, 5, "Another part of the field.", 5, "henry4p1" },
                    { 18914, 0, "Warkworth. Before NORTHUMBERLAND’S Castle", 1, "henry4p2" },
                    { 18915, 1, "Warkworth. Before NORTHUMBERLAND’S Castle", 1, "henry4p2" },
                    { 18916, 1, "London. A street", 2, "henry4p2" },
                    { 18917, 1, "York. The ARCHBISHOP’S palace", 3, "henry4p2" },
                    { 18918, 2, "London. A street", 1, "henry4p2" },
                    { 18919, 2, "London. Another street", 2, "henry4p2" },
                    { 18920, 2, "Warkworth. Before the castle", 3, "henry4p2" },
                    { 18921, 2, "London. The Boar’s Head Tavern in Eastcheap", 4, "henry4p2" },
                    { 18922, 3, "Westminster. The palace", 1, "henry4p2" },
                    { 18923, 3, "Gloucestershire. Before Justice, SHALLOW’S house", 2, "henry4p2" },
                    { 18924, 4, "Yorkshire. Within the Forest of Gaultree", 1, "henry4p2" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18925, 4, "Another part of the forest", 2, "henry4p2" },
                    { 18926, 4, "Another part of the forest", 3, "henry4p2" },
                    { 18927, 4, "Westminster. The Jerusalem Chamber", 4, "henry4p2" },
                    { 18928, 4, "Westminster. Another chamber", 5, "henry4p2" },
                    { 18929, 5, "Gloucestershire. SHALLOW’S house", 1, "henry4p2" },
                    { 18930, 5, "Westminster. The palace", 2, "henry4p2" },
                    { 18931, 5, "Gloucestershire. SHALLOW’S orchard", 3, "henry4p2" },
                    { 18932, 5, "London. A street", 4, "henry4p2" },
                    { 18933, 5, "Westminster. Near the Abbey", 5, "henry4p2" },
                    { 18934, 0, "Prologue.", 1, "henry5" },
                    { 18935, 1, "London. An ante-chamber in the KING’S palace.", 1, "henry5" },
                    { 18936, 1, "The same. The Presence chamber.", 2, "henry5" },
                    { 18911, 5, "Plain between the camps.", 3, "henry4p1" },
                    { 18910, 5, "The rebel camp.", 2, "henry4p1" },
                    { 18909, 5, "KING HENRY IV’s camp near Shrewsbury.", 1, "henry4p1" },
                    { 18908, 4, "York. The ARCHBISHOP’S palace.", 4, "henry4p1" },
                    { 18882, 3, "Elsinore. A room in the Castle.", 1, "hamlet" },
                    { 18883, 3, "Elsinore. hall in the Castle.", 2, "hamlet" },
                    { 18884, 3, "A room in the Castle.", 3, "hamlet" },
                    { 18885, 3, "The Queen’s closet.", 4, "hamlet" },
                    { 18886, 4, "Elsinore. A room in the Castle.", 1, "hamlet" },
                    { 18887, 4, "Elsinore. A passage in the Castle.", 2, "hamlet" },
                    { 18888, 4, "Elsinore. A room in the Castle.", 3, "hamlet" },
                    { 18889, 4, "Near Elsinore.", 4, "hamlet" },
                    { 18890, 4, "Elsinore. A room in the Castle.", 5, "hamlet" },
                    { 18891, 4, "Elsinore. Another room in the Castle.", 6, "hamlet" },
                    { 18892, 4, "Elsinore. Another room in the Castle.", 7, "hamlet" },
                    { 18893, 5, "Elsinore. A churchyard.", 1, "hamlet" },
                    { 18880, 2, "Elsinore. A room in the house of Polonius.", 1, "hamlet" },
                    { 18894, 5, "Elsinore. A hall in the Castle.", 2, "hamlet" },
                    { 18896, 1, "London. An apartment of the Prince’s.", 2, "henry4p1" },
                    { 18897, 1, "London. The palace.", 3, "henry4p1" },
                    { 18898, 2, "Rochester. An inn yard.", 1, "henry4p1" },
                    { 18899, 2, "The highway, near Gadshill.", 2, "henry4p1" },
                    { 18900, 2, "Warkworth castle", 3, "henry4p1" },
                    { 18901, 2, "The Boar’s-Head Tavern, Eastcheap.", 4, "henry4p1" },
                    { 18902, 3, "Bangor. The Archdeacon’s house.", 1, "henry4p1" },
                    { 18903, 3, "London. The palace.", 2, "henry4p1" },
                    { 18904, 3, "Eastcheap. The Boar’s-Head Tavern.", 3, "henry4p1" },
                    { 18905, 4, "The rebel camp near Shrewsbury.", 1, "henry4p1" },
                    { 18906, 4, "A public road near Coventry.", 2, "henry4p1" },
                    { 18907, 4, "The rebel camp near Shrewsbury.", 3, "henry4p1" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18895, 1, "London. The palace.", 1, "henry4p1" },
                    { 18937, 2, "Prologue.", 0, "henry5" },
                    { 18821, 1, "Corioli. The Senate-house.", 2, "coriolanus" },
                    { 18819, 5, "A street before a Priory.", 1, "comedyerrors" },
                    { 18735, 3, "Camp before Florence.", 6, "allswell" },
                    { 18736, 3, "Florence. The Widow’s house.", 7, "allswell" },
                    { 18737, 4, "Without the Florentine camp.", 1, "allswell" },
                    { 18738, 4, "Florence. The Widow’s house.", 2, "allswell" },
                    { 18739, 4, "The Florentine camp.", 3, "allswell" },
                    { 18740, 4, "Florence. The Widow’s house.", 4, "allswell" },
                    { 18741, 4, "Rousillon. The COUNT’s palace.", 5, "allswell" },
                    { 18742, 5, "Marseilles. A street.", 1, "allswell" },
                    { 18743, 5, "Rousillon. Before the COUNT’s palace.", 2, "allswell" },
                    { 18744, 5, "Rousillon. The COUNT’s palace.", 3, "allswell" },
                    { 18745, 1, "Alexandria. A room in CLEOPATRA’s palace.", 1, "antonycleo" },
                    { 18746, 1, "The same. Another room.", 2, "antonycleo" },
                    { 18747, 1, "The same. Another room.", 3, "antonycleo" },
                    { 18748, 1, "Rome. OCTAVIUS CAESAR’s house.", 4, "antonycleo" },
                    { 18749, 1, "Alexandria. CLEOPATRA’s palace.", 5, "antonycleo" },
                    { 18750, 2, "Messina. POMPEY’s house.", 1, "antonycleo" },
                    { 18751, 2, "Rome. The house of LEPIDUS.", 2, "antonycleo" },
                    { 18752, 2, "The same. OCTAVIUS CAESAR’s house.", 3, "antonycleo" },
                    { 18753, 2, "The same. A street.", 4, "antonycleo" },
                    { 18754, 2, "Alexandria. CLEOPATRA’s palace.", 5, "antonycleo" },
                    { 18755, 2, "Near Misenum.", 6, "antonycleo" },
                    { 18756, 2, "On board POMPEY’s galley, off Misenum.", 7, "antonycleo" },
                    { 18757, 3, "A plain in Syria.", 1, "antonycleo" },
                    { 18758, 3, "Rome. An ante-chamber in OCTAVIUS CAESAR’s house.", 2, "antonycleo" },
                    { 18759, 3, "Alexandria. CLEOPATRA’s palace.", 3, "antonycleo" },
                    { 18734, 3, "Florence. Without the walls. A tucket afar off.", 5, "allswell" },
                    { 18733, 3, "Rousillon. The COUNT’s palace.", 4, "allswell" },
                    { 18732, 3, "Florence. Before the DUKE’s palace.", 3, "allswell" },
                    { 18731, 3, "Rousillon. The COUNT’s palace.", 2, "allswell" },
                    { 18705, 1, "The sea-coast.", 2, "12night" },
                    { 18706, 1, "OLIVIA’S house.", 3, "12night" },
                    { 18707, 1, "DUKE ORSINO’s palace.", 4, "12night" },
                    { 18708, 1, "OLIVIA’S house.", 5, "12night" },
                    { 18709, 2, "The sea-coast.", 1, "12night" },
                    { 18710, 2, "A street.", 2, "12night" },
                    { 18711, 2, "OLIVIA’s house.", 3, "12night" },
                    { 18712, 2, "DUKE ORSINO’s palace.", 4, "12night" },
                    { 18713, 2, "OLIVIA’s garden.", 5, "12night" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18714, 3, "OLIVIA’s garden.", 1, "12night" },
                    { 18715, 3, "OLIVIA’s house.", 2, "12night" },
                    { 18716, 3, "A street.", 3, "12night" },
                    { 18760, 3, "Athens. A room in MARK ANTONY’s house.", 4, "antonycleo" },
                    { 18717, 3, "OLIVIA’s garden.", 4, "12night" },
                    { 18719, 4, "OLIVIA’s house.", 2, "12night" },
                    { 18720, 4, "OLIVIA’s garden.", 3, "12night" },
                    { 18721, 5, "Before OLIVIA’s house.", 1, "12night" },
                    { 18722, 1, "Rousillon. The COUNT’s palace.", 1, "allswell" },
                    { 18723, 1, "Paris. The KING’s palace.", 2, "allswell" },
                    { 18724, 1, "Rousillon. The COUNT’s palace.", 3, "allswell" },
                    { 18725, 2, "Paris. The KING’s palace.", 1, "allswell" },
                    { 18726, 2, "Rousillon. The COUNT’s palace.", 2, "allswell" },
                    { 18727, 2, "Paris. The KING’s palace.", 3, "allswell" },
                    { 18728, 2, "Paris. The KING’s palace.", 4, "allswell" },
                    { 18729, 2, "Paris. The KING’s palace.", 5, "allswell" },
                    { 18730, 3, "Florence. The DUKE’s palace.", 1, "allswell" },
                    { 18718, 4, "Before OLIVIA’s house.", 1, "12night" },
                    { 18820, 1, "Rome. A street.", 1, "coriolanus" },
                    { 18761, 3, "The same. Another room.", 5, "antonycleo" },
                    { 18763, 3, "Near Actium. MARK ANTONY’s camp.", 7, "antonycleo" },
                    { 18794, 2, "Another part of the forest", 5, "asyoulikeit" },
                    { 18795, 2, "The forest", 6, "asyoulikeit" },
                    { 18796, 2, "The forest", 7, "asyoulikeit" },
                    { 18797, 3, "The palace", 1, "asyoulikeit" },
                    { 18798, 3, "The forest", 2, "asyoulikeit" },
                    { 18799, 3, "The forest", 3, "asyoulikeit" },
                    { 18800, 3, "The forest", 4, "asyoulikeit" },
                    { 18801, 3, "Another part of the forest", 5, "asyoulikeit" },
                    { 18802, 4, "The forest", 1, "asyoulikeit" },
                    { 18803, 4, "The forest", 2, "asyoulikeit" },
                    { 18804, 4, "The forest", 3, "asyoulikeit" },
                    { 18805, 5, "The forest", 1, "asyoulikeit" },
                    { 18806, 5, "The forest", 2, "asyoulikeit" },
                    { 18807, 5, "The forest", 3, "asyoulikeit" },
                    { 18808, 5, "The forest", 4, "asyoulikeit" },
                    { 18809, 1, "A hall in DUKE SOLINUS’S palace.", 1, "comedyerrors" },
                    { 18810, 1, "The Mart.", 2, "comedyerrors" },
                    { 18811, 2, "The house of ANTIPHOLUS of Ephesus.", 1, "comedyerrors" },
                    { 18812, 2, "A public place.", 2, "comedyerrors" },
                    { 18813, 3, "Before the house of ANTIPHOLUS of Ephesus.", 1, "comedyerrors" },
                    { 18814, 3, "The same.", 2, "comedyerrors" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18815, 4, "A public place.", 1, "comedyerrors" },
                    { 18816, 4, "The house of ANTIPHOLUS of Ephesus.", 2, "comedyerrors" },
                    { 18817, 4, "A public place.", 3, "comedyerrors" },
                    { 18818, 4, "A street.", 4, "comedyerrors" },
                    { 18793, 2, "The Forest of Arden", 4, "asyoulikeit" },
                    { 18792, 2, "Before OLIVER’S house", 3, "asyoulikeit" },
                    { 18791, 2, "The DUKE’S palace", 2, "asyoulikeit" },
                    { 18790, 2, "The Forest of Arden", 1, "asyoulikeit" },
                    { 18764, 3, "A plain near Actium.", 8, "antonycleo" },
                    { 18765, 3, "Another part of the plain.", 9, "antonycleo" },
                    { 18766, 3, "Another part of the plain.\r\n", 10, "antonycleo" },
                    { 18767, 3, "Alexandria. CLEOPATRA’s palace.\r\n", 11, "antonycleo" },
                    { 18768, 3, "Egypt. OCTAVIUS CAESAR’s camp.\r\n", 12, "antonycleo" },
                    { 18769, 3, "Alexandria. CLEOPATRA’s palace.\r\n", 13, "antonycleo" },
                    { 18770, 4, "Before Alexandria. OCTAVIUS CAESAR’s camp.", 1, "antonycleo" },
                    { 18771, 4, "Alexandria. CLEOPATRA’s palace.", 2, "antonycleo" },
                    { 18772, 4, "The same. Before the palace.", 3, "antonycleo" },
                    { 18773, 4, "The same. A room in the palace.", 4, "antonycleo" },
                    { 18774, 4, "Alexandria. MARK ANTONY’s camp.", 5, "antonycleo" },
                    { 18775, 4, "Alexandria. OCTAVIUS CAESAR’s camp.", 6, "antonycleo" },
                    { 18762, 3, "Rome. OCTAVIUS CAESAR’s house.", 6, "antonycleo" },
                    { 18776, 4, "Field of battle between the camps.", 7, "antonycleo" },
                    { 18778, 4, "OCTAVIUS CAESAR’s camp.", 9, "antonycleo" },
                    { 18779, 4, "Between the two camps.\r\n", 10, "antonycleo" },
                    { 18780, 4, "Another part of the same.\r\n", 11, "antonycleo" },
                    { 18781, 4, "Another part of the same.\r\n", 12, "antonycleo" },
                    { 18782, 4, "Alexandria. Cleopatra’s palace.\r\n", 13, "antonycleo" },
                    { 18783, 4, "The same. Another room.\r\n", 14, "antonycleo" },
                    { 18784, 4, "The same. A monument.\r\n", 15, "antonycleo" },
                    { 18785, 5, "Alexandria. OCTAVIUS CAESAR’s camp.", 1, "antonycleo" },
                    { 18786, 5, "Alexandria. A room in the monument.", 2, "antonycleo" },
                    { 18787, 1, "Orchard of OLIVER’S house", 1, "asyoulikeit" },
                    { 18788, 1, "A lawn before the DUKE’S palace", 2, "asyoulikeit" },
                    { 18789, 1, "The DUKE’s palace", 3, "asyoulikeit" },
                    { 18777, 4, "Under the walls of Alexandria.", 8, "antonycleo" },
                    { 18938, 2, "London. A street.", 1, "henry5" },
                    { 18939, 2, "Southampton. A council-chamber.", 2, "henry5" },
                    { 18940, 2, "London. Before a tavern.", 3, "henry5" },
                    { 19090, 5, "The French camp.", 5, "kingjohn" },
                    { 19091, 5, "An open place in the neighbourhood of Swinstead Abbey.", 6, "kingjohn" },
                    { 19092, 5, "The orchard in Swinstead Abbey.", 7, "kingjohn" },
                    { 19093, 1, "King Lear’s Palace.", 1, "kinglear" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19094, 1, "The Earl of Gloucester’s Castle.", 2, "kinglear" },
                    { 19095, 1, "The Duke of Albany’s Palace.", 3, "kinglear" },
                    { 19096, 1, "The Duke of Albany’s Palace. Enter Kent, [disguised].", 4, "kinglear" },
                    { 19097, 1, "Court before the Duke of Albany’s Palace. Enter Lear, Kent, and Fool.", 5, "kinglear" },
                    { 19098, 2, "A court within the Castle of the Earl of Gloucester.", 1, "kinglear" },
                    { 19099, 2, "Before Gloucester’s Castle. Enter Kent and [Oswald the] Steward, severally.", 2, "kinglear" },
                    { 19100, 2, "The open country.", 3, "kinglear" },
                    { 19101, 2, "Before Gloucester’s Castle; Kent in the stocks.", 4, "kinglear" },
                    { 19102, 3, "A heath. Storm still.", 1, "kinglear" },
                    { 19103, 3, "Another part of the heath. Storm still.", 2, "kinglear" },
                    { 19104, 3, "Gloucester’s Castle.", 3, "kinglear" },
                    { 19105, 3, "The heath. Before a hovel. Storm still.", 4, "kinglear" },
                    { 19106, 3, "Gloucester’s Castle.", 5, "kinglear" },
                    { 19107, 3, "A farmhouse near Gloucester’s Castle.", 6, "kinglear" },
                    { 19108, 3, "Gloucester’s Castle. Enter Cornwall, Regan, Goneril, [Edmund the] Bastard, and Servants.", 7, "kinglear" },
                    { 19109, 4, "The heath.", 1, "kinglear" },
                    { 19110, 4, "Before the Duke of Albany’s Palace.", 2, "kinglear" },
                    { 19111, 4, "The French camp near Dover.", 3, "kinglear" },
                    { 19112, 4, "The French camp.", 4, "kinglear" },
                    { 19113, 4, "Gloucester’s Castle.", 5, "kinglear" },
                    { 19114, 4, "The country near Dover. Enter Gloucester, and Edgar [like a Peasant].", 6, "kinglear" },
                    { 19089, 5, "Another part of the field.", 4, "kingjohn" },
                    { 19088, 5, "The field of battle.", 3, "kingjohn" },
                    { 19087, 5, "LEWIS’s camp at St. Edmundsbury.", 2, "kingjohn" },
                    { 19086, 5, "KING JOHN’S palace.", 1, "kingjohn" },
                    { 19060, 1, "A public place.", 2, "juliuscaesar" },
                    { 19061, 1, "The same. A street.", 3, "juliuscaesar" },
                    { 19062, 2, "Rome. BRUTUS’s orchard.", 1, "juliuscaesar" },
                    { 19063, 2, "CAESAR’s house.", 2, "juliuscaesar" },
                    { 19064, 2, "A street near the Capitol.", 3, "juliuscaesar" },
                    { 19065, 2, "Another part of the same street, before the house of BRUTUS.", 4, "juliuscaesar" },
                    { 19066, 3, "Rome. Before the Capitol; the Senate sitting above.", 1, "juliuscaesar" },
                    { 19067, 3, "The Forum.", 2, "juliuscaesar" },
                    { 19068, 3, "A street.", 3, "juliuscaesar" },
                    { 19069, 4, "A house in Rome.", 1, "juliuscaesar" },
                    { 19070, 4, "Camp near Sardis. Before BRUTUS’s tent.", 2, "juliuscaesar" },
                    { 19071, 4, "Brutus’s tent.", 3, "juliuscaesar" },
                    { 19115, 4, "A tent in the French camp.", 7, "kinglear" },
                    { 19072, 5, "The plains of Philippi.", 1, "juliuscaesar" },
                    { 19074, 5, "Another part of the field.", 3, "juliuscaesar" },
                    { 19075, 5, "Another part of the field.", 4, "juliuscaesar" },
                    { 19076, 5, "Another part of the field.", 5, "juliuscaesar" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19077, 1, "KING JOHN’S palace.", 1, "kingjohn" },
                    { 19078, 2, "France. Before Angiers.", 1, "kingjohn" },
                    { 19079, 3, "The French King’s pavilion.", 1, "kingjohn" },
                    { 19080, 3, "The same. Plains near Angiers.", 2, "kingjohn" },
                    { 19081, 3, "The same.", 3, "kingjohn" },
                    { 19082, 3, "The same. KING PHILIP’S tent.", 4, "kingjohn" },
                    { 19083, 4, "A room in a castle.", 1, "kingjohn" },
                    { 19084, 4, "KING JOHN’S palace.", 2, "kingjohn" },
                    { 19085, 4, "Before the castle.", 3, "kingjohn" },
                    { 19073, 5, "The same. The field of battle.", 2, "juliuscaesar" },
                    { 19059, 1, "Rome. A street.", 1, "juliuscaesar" },
                    { 19116, 5, "The British camp near Dover.", 1, "kinglear" },
                    { 19118, 5, "The British camp, near Dover.", 3, "kinglear" },
                    { 19149, 5, "Dunsinane. Ante-room in the castle.", 1, "macbeth" },
                    { 19150, 5, "The country near Dunsinane.", 2, "macbeth" },
                    { 19151, 5, "Dunsinane. A room in the castle.", 3, "macbeth" },
                    { 19152, 5, "Country near Birnam wood.", 4, "macbeth" },
                    { 19153, 5, "Dunsinane. Within the castle.", 5, "macbeth" },
                    { 19154, 5, "Dunsinane. Before the castle.", 6, "macbeth" },
                    { 19155, 5, "Another part of the field.", 7, "macbeth" },
                    { 19156, 5, "Another part of the field.", 8, "macbeth" },
                    { 19157, 1, "An apartment in the DUKE’S palace.", 1, "measure" },
                    { 19158, 1, "A Street.", 2, "measure" },
                    { 19159, 1, "A monastery.", 3, "measure" },
                    { 19160, 1, "A nunnery.", 4, "measure" },
                    { 19161, 2, "A hall In ANGELO’s house.", 1, "measure" },
                    { 19162, 2, "Another room in the same.", 2, "measure" },
                    { 19163, 2, "A room in a prison.", 3, "measure" },
                    { 19164, 2, "A room in ANGELO’s house.", 4, "measure" },
                    { 19165, 3, "A room in the prison.", 1, "measure" },
                    { 19166, 3, "The street before the prison.", 2, "measure" },
                    { 19167, 4, "The moated grange at ST. LUKE’s.", 1, "measure" },
                    { 19168, 4, "A room in the prison.", 2, "measure" },
                    { 19169, 4, "Another room in the same.", 3, "measure" },
                    { 19170, 4, "A room in ANGELO’s house.", 4, "measure" },
                    { 19171, 4, "Fields without the town.", 5, "measure" },
                    { 19172, 4, "Street near the city gate.", 6, "measure" },
                    { 19173, 5, "The city gate.", 1, "measure" },
                    { 19148, 4, "England. Before the King’s palace.", 3, "macbeth" },
                    { 19147, 4, "Fife. Macduff’s castle.", 2, "macbeth" },
                    { 19146, 4, "A cavern. In the middle, a boiling cauldron.", 1, "macbeth" },
                    { 19145, 3, "Forres. The palace.", 6, "macbeth" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19119, 1, "A Lover’s Complaint.", 1, "loverscomplaint" },
                    { 19120, 1, "The king of Navarre’s park.", 1, "loveslabours" },
                    { 19121, 1, "The same.", 2, "loveslabours" },
                    { 19122, 2, "The same.", 1, "loveslabours" },
                    { 19123, 3, "The same.", 1, "loveslabours" },
                    { 19124, 4, "The same.", 1, "loveslabours" },
                    { 19125, 4, "The same.", 2, "loveslabours" },
                    { 19126, 4, "The same.", 3, "loveslabours" },
                    { 19127, 5, "The same.", 1, "loveslabours" },
                    { 19128, 5, "The same.", 2, "loveslabours" },
                    { 19129, 1, "A desert place.", 1, "macbeth" },
                    { 19130, 1, "A camp near Forres.", 2, "macbeth" },
                    { 19117, 5, "A field between the two camps. Alarum within.", 2, "kinglear" },
                    { 19131, 1, "A heath near Forres.", 3, "macbeth" },
                    { 19133, 1, "Inverness. Macbeth’s castle.", 5, "macbeth" },
                    { 19134, 1, "Before Macbeth’s castle.", 6, "macbeth" },
                    { 19135, 1, "Macbeth’s castle.", 7, "macbeth" },
                    { 19136, 2, "Court of Macbeth’s castle.", 1, "macbeth" },
                    { 19137, 2, "The same.", 2, "macbeth" },
                    { 19138, 2, "The same.", 3, "macbeth" },
                    { 19139, 2, "Outside Macbeth’s castle.", 4, "macbeth" },
                    { 19140, 3, "Forres. The palace.", 1, "macbeth" },
                    { 19141, 3, "The palace.", 2, "macbeth" },
                    { 19142, 3, "A park near the palace.", 3, "macbeth" },
                    { 19143, 3, "The same. Hall in the palace.", 4, "macbeth" },
                    { 19144, 3, "A Heath.", 5, "macbeth" },
                    { 19132, 1, "Forres. The palace.", 4, "macbeth" },
                    { 19058, 5, "The palace.", 5, "henry8" },
                    { 19057, 5, "The palace yard.", 4, "henry8" },
                    { 19056, 5, "The Council-Chamber.", 3, "henry8" },
                    { 18971, 2, "London. The Temple-garden.", 4, "henry6p1" },
                    { 18972, 2, "The Tower of London.", 5, "henry6p1" },
                    { 18973, 3, "London. The Parliament-house.", 1, "henry6p1" },
                    { 18974, 3, "France. Before Rouen.", 2, "henry6p1" },
                    { 18975, 3, "The plains near Rouen.", 3, "henry6p1" },
                    { 18976, 3, "Paris. The palace.", 4, "henry6p1" },
                    { 18977, 4, "Paris. A hall of state.", 1, "henry6p1" },
                    { 18978, 4, "Before Bourdeaux.", 2, "henry6p1" },
                    { 18979, 4, "Plains in Gascony.", 3, "henry6p1" },
                    { 18980, 4, "Other plains in Gascony.", 4, "henry6p1" },
                    { 18981, 4, "The English camp near Bourdeaux.", 5, "henry6p1" },
                    { 18982, 4, "A field of battle.", 6, "henry6p1" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18983, 4, "Another part of the field.", 7, "henry6p1" },
                    { 18984, 5, "London. The palace.", 1, "henry6p1" },
                    { 18985, 5, "France. Plains in Anjou.", 2, "henry6p1" },
                    { 18986, 5, "Before Angiers.", 3, "henry6p1" },
                    { 18987, 5, "Camp of the YORK in Anjou.", 4, "henry6p1" },
                    { 18988, 5, "London. The palace.", 5, "henry6p1" },
                    { 18989, 1, "London. The palace.", 1, "henry6p2" },
                    { 18990, 1, "GLOUCESTER’S house.", 2, "henry6p2" },
                    { 18991, 1, "The palace.", 3, "henry6p2" },
                    { 18992, 1, "GLOUCESTER’s garden.", 4, "henry6p2" },
                    { 18993, 2, "Saint Alban’s.", 1, "henry6p2" },
                    { 18994, 2, "London. YORK’S garden.", 2, "henry6p2" },
                    { 18995, 2, "A hall of justice.", 3, "henry6p2" },
                    { 18970, 2, "Auvergne. The COUNTESS’s castle.", 3, "henry6p1" },
                    { 18969, 2, "Orleans. Within the town.", 2, "henry6p1" },
                    { 18968, 2, "Before Orleans.", 1, "henry6p1" },
                    { 18967, 1, "The same.", 6, "henry6p1" },
                    { 18941, 2, "France. The KING’S palace.", 4, "henry5" },
                    { 18942, 3, "Prologue.", 0, "henry5" },
                    { 18943, 3, "France. Before Harfleur.", 1, "henry5" },
                    { 18944, 3, "The same.", 2, "henry5" },
                    { 18945, 3, "The same. Before the gates.", 3, "henry5" },
                    { 18946, 3, "The FRENCH KING’s palace.", 4, "henry5" },
                    { 18947, 3, "The same.", 5, "henry5" },
                    { 18948, 3, "The English camp in Picardy.", 6, "henry5" },
                    { 18949, 3, "The French camp, near Agincourt:", 7, "henry5" },
                    { 18950, 4, "Prologue.", 0, "henry5" },
                    { 18951, 4, "The English camp at Agincourt.", 1, "henry5" },
                    { 18952, 4, "The French camp.", 2, "henry5" },
                    { 18996, 2, "A street.", 4, "henry6p2" },
                    { 18953, 4, "The English camp.", 3, "henry5" },
                    { 18955, 4, "Another part of the field.", 5, "henry5" },
                    { 18956, 4, "Another part of the field.", 6, "henry5" },
                    { 18957, 4, "Another part of the field.", 7, "henry5" },
                    { 18958, 4, "Before KING HENRY’S pavilion.", 8, "henry5" },
                    { 18959, 5, "Prologue.", 0, "henry5" },
                    { 18960, 5, "France. The English camp.", 1, "henry5" },
                    { 18961, 5, "France. A royal palace.", 2, "henry5" },
                    { 18962, 1, "Westminster Abbey.", 1, "henry6p1" },
                    { 18963, 1, "France. Before Orleans.", 2, "henry6p1" },
                    { 18964, 1, "London. Before the Tower.", 3, "henry6p1" },
                    { 18965, 1, "Orleans.", 4, "henry6p1" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 18966, 1, "The same.", 5, "henry6p1" },
                    { 18954, 4, "The field of battle.", 4, "henry5" },
                    { 18997, 3, "The Abbey at Bury St. Edmund’s.", 1, "henry6p2" },
                    { 18998, 3, "Bury St. Edmund’s. A room of state.", 2, "henry6p2" },
                    { 18999, 3, "A bedchamber.", 3, "henry6p2" },
                    { 19030, 4, "A park near Middleham Castle In Yorkshire.", 5, "henry6p3" },
                    { 19031, 4, "London. The Tower.", 6, "henry6p3" },
                    { 19032, 4, "Before York.", 7, "henry6p3" },
                    { 19033, 4, "London. The palace.", 8, "henry6p3" },
                    { 19034, 5, "Coventry.", 1, "henry6p3" },
                    { 19035, 5, "A field of battle near Barnet.", 2, "henry6p3" },
                    { 19036, 5, "Another part of the field.", 3, "henry6p3" },
                    { 19037, 5, "Plains near Tewksbury.", 4, "henry6p3" },
                    { 19038, 5, "Another part of the field.", 5, "henry6p3" },
                    { 19039, 5, "London. The Tower.", 6, "henry6p3" },
                    { 19040, 5, "London. The palace.", 7, "henry6p3" },
                    { 19041, 1, "Prologue.", 0, "henry8" },
                    { 19029, 4, "London. The palace.", 4, "henry6p3" },
                    { 19042, 1, "London. An ante-chamber in the palace.", 1, "henry8" },
                    { 19044, 1, "An ante-chamber in the palace.", 3, "henry8" },
                    { 19045, 1, "A Hall in York Place.", 4, "henry8" },
                    { 19046, 2, "Westminster. A street.", 1, "henry8" },
                    { 19047, 2, "An ante-chamber in the palace.", 2, "henry8" },
                    { 19048, 2, "An ante-chamber of the QUEEN’S apartments.", 3, "henry8" },
                    { 19049, 2, "A hall in Black-Friars.", 4, "henry8" },
                    { 19050, 3, "London. QUEEN KATHARINE’s apartments.", 1, "henry8" },
                    { 19051, 3, "Ante-chamber to KING HENRY VIII’s apartment.", 2, "henry8" },
                    { 19052, 4, "A street in Westminster.", 1, "henry8" },
                    { 19053, 4, "Kimbolton.", 2, "henry8" },
                    { 19054, 5, "London. A gallery in the palace.", 1, "henry8" },
                    { 19055, 5, "Before the council-chamber. Pursuivants, Pages, &c.", 2, "henry8" },
                    { 19043, 1, "The same. The council-chamber.", 2, "henry8" },
                    { 19175, 1, "Belmont. A room in PORTIA’S house.", 2, "merchantvenice" },
                    { 19028, 4, "Edward’s camp, near Warwick.", 3, "henry6p3" },
                    { 19026, 4, "London. The palace.", 1, "henry6p3" },
                    { 19000, 4, "The coast of Kent.", 1, "henry6p2" },
                    { 19001, 4, "Blackheath.", 2, "henry6p2" },
                    { 19002, 4, "Another part of Blackheath.", 3, "henry6p2" },
                    { 19003, 4, "London. The palace.", 4, "henry6p2" },
                    { 19004, 4, "London. The Tower.", 5, "henry6p2" },
                    { 19005, 4, "London. Cannon Street.", 6, "henry6p2" },
                    { 19006, 4, "London. Smithfield.", 7, "henry6p2" }
                });

            migrationBuilder.InsertData(
                table: "Chapters",
                columns: new[] { "ChapterId", "Act", "Description", "Scene", "WorkId" },
                values: new object[,]
                {
                    { 19007, 4, "Southwark.", 8, "henry6p2" },
                    { 19008, 4, "Kenilworth Castle.", 9, "henry6p2" },
                    { 19009, 4, "Kent. IDEN’s garden.\r\n", 10, "henry6p2" },
                    { 19010, 5, "Fields between Dartford and Blackheath.", 1, "henry6p2" },
                    { 19011, 5, "Saint Alban’s.", 2, "henry6p2" },
                    { 19027, 4, "A plain in Warwickshire.", 2, "henry6p3" },
                    { 19012, 5, "Fields near St. Alban’s.", 3, "henry6p2" },
                    { 19014, 1, "Sandal Castle.", 2, "henry6p3" },
                    { 19015, 1, "Field of battle betwixt Sandal Castle and Wakefield.", 3, "henry6p3" },
                    { 19016, 1, "Another part of the field.", 4, "henry6p3" },
                    { 19017, 2, "A plain near Mortimer’s Cross in Herefordshire.", 1, "henry6p3" },
                    { 19018, 2, "Before York.", 2, "henry6p3" },
                    { 19019, 2, "A field of battle between Towton and Saxton, in", 3, "henry6p3" },
                    { 19020, 2, "Another part of the field.", 4, "henry6p3" },
                    { 19021, 2, "Another part of the field.", 5, "henry6p3" },
                    { 19022, 2, "Another part of the field.", 6, "henry6p3" },
                    { 19023, 3, "A forest in the north of England.", 1, "henry6p3" },
                    { 19024, 3, "London. The palace.", 2, "henry6p3" },
                    { 19025, 3, "France. KING LEWIS XI’s palace.", 3, "henry6p3" },
                    { 19013, 1, "London. The Parliament-house.", 1, "henry6p3" },
                    { 19648, 5, "A chapel in PAULINA’S house.", 3, "winterstale" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Commands_PlatformId",
                table: "Commands",
                column: "PlatformId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Chapters");

            migrationBuilder.DropTable(
                name: "Commands");

            migrationBuilder.DropTable(
                name: "Platforms");
        }
    }
}
